dejan/rails_panel

- .travis.yml
- meta_request/lib/meta_request/event.rb
Requiring `active_support` before `active_support/core_ext` is necessary.
Update bundler's version before bundle install.
https://github.com/bundler/bundler/issues/3558
> Fix CI failure

- meta_request/meta_request.gemspec
When I ran `rake test:unit` in meta_request for rails 5.0.0.beta1, it could pass all tests.
So I relaxed dependency for rails to under 5.1.
> Accept rails 5.0 for meta_request

- meta_request/lib/meta_request/app_notifications.rb
- rails_panel/assets/javascripts/transactions.js
- rails_panel/panel.html
1. add a tab for active_support cache instrumentation 
2. fix bug where html generated from `ansi2html` wouldn't be rendered - i tested this by logging html and something in color and the html remains escaped while the added colors are converted to html and rendered correctly.
> add cache tab, fix rendering of color logging

- README.md
- rails_panel/assets/javascripts/filters.js
- rails_panel/options.html
Adds support for the text editor Atom, via [atom-handler](https://github.com/WizardOfOgz/atom-handler), as suggested by @zenry.
Three small changes were required:
1. A radio button is added to the chrome extension's options. It has a link to atom-handler.
2. The mapping hash of editorPrefixes was extended to include the [textmate style URL](https://github.com/WizardOfOgz/atom-handler#examples) for atom-handler.
3. The repo's README.md was updated to reflect support for Atom.
Merging this request closes #82
> Adds support for the text editor Atom

- meta_request/lib/meta_request/middlewares/app_request_handler.rb
`ActionDispatch::ExceptionWrapper.new`'s first argument is `backtrace_cleaner` instead of `env` in Rails 5.
SEE ALSO:
https://github.com/rails/rails/commit/6d85804bc6aeecce5669fb4b0d7b33c069deff3a
> follow the Rails 5 specification

- meta_request/lib/meta_request/log_interceptor.rb
When extending `Rails.logger` with `MetaRequest::LogInterceptor`, the method signature of the
base logger should be preserved, rather than limiting to a single argument.  Some logging classes
allow multiple arguments *and* can serve as `Logger` substitutes, and `LogInterceptor` is breaking
other callers to those logging classes.
An example error:
```ruby
{
:exception => "ArgumentError",
:message   => "wrong number of arguments (given 2, expected 0..1)",
:backtrace => [
[ 0] "gems/meta_request-0.3.4/lib/meta_request/log_interceptor.rb:11:in `info'",
]
}
```
This pull request passes the argument list to the original class unmodified, which fixes the issue we are experiencing.
Thanks for considering this PR.  ~~Some additional work may be needed to ensure all tests still pass on all Ruby …
> Don't override method signatures of base logger

- meta_request/meta_request.gemspec
For proper Rails 5.1 support. See #121
> Change railties version to "< 5.2.0" in dependencies

- rails_panel/assets/stylesheets/panel.css
I recently noticed that after upgrading `meta_request` the tab names and anchor hit area were hidden. This PR modifies the plugin's css to ensure that the names are visible and hit areas are larger. See screenshots below for issue. 
Missing tab names
Missing hit area for clicking tabs
**After Fix**
> Fix missing tab names and hit area in panel

- meta_request/lib/meta_request/app_notifications.rb
this hacks in sequel support by pretending it's `sql.active_record` data.
i'm not sure it's the right solution but i'm hesitant to make any ui changes. i thought about altering the tab's title based on some flag but i don't know if people would potentially be using `sequel` _and_ `activerecord` at the same time. for now this probably is a good enough solution?
> add sql.sequel support

- rails_panel/assets/javascripts/background.js
- rails_panel/assets/javascripts/requests.js
Fixes #142. Needed to return true in onMessage so the getJSON callback is called asynchronously. I also noticed deprecated extension functions were being called, so I switched to the recommended runtime functions instead.
> Fix empty rails panel in Chrome

- rails_panel/panel.html
When location is missing (`payload.filename` is undefined) `normalizePath` function throws an error and raw, unprocessed Angular string is rendered.
Solution copied from https://github.com/gogiel/rails_panel/blob/b5f48b8f4bcde377b5e885b4ef60170efe43f6ac/rails_panel/panel.html#L210-L214
> Handle missing SQL location

- meta_request/.gitignore
- meta_request/lib/meta_request/config.rb
- meta_request/test/unit/meta_request/config_test.rb
attr_writers were accidentally removed by me at https://github.com/dejan/rails_panel/commit/1f1a4d309596d39bb81213361458d99f5740505b#diff-4ade6c3c1b1d1315271db7ac73495c5e
This PR reverts it and adds a test.
> Add missing attr_writers to config

- meta_request/README.md
- meta_request/lib/meta_request/app_notifications.rb
- meta_request/lib/meta_request/config.rb
- meta_request/lib/meta_request/log_interceptor.rb
- meta_request/lib/meta_request/utils.rb
- meta_request/meta_request.gemspec
- meta_request/test/unit/meta_request/utils_test.rb
The change addresses the problem described in: https://github.com/dejan/rails_panel/issues/128
The new config option is added that allows override of the source path (by default it's Rails.root). Using this it's possible to run the app in the Docker container and still get the correct file paths (from the host system):
```yaml
services:
app:
environment:
- SOURCE_PATH=$PWD
```
> Introduce source_path configuration

- rails_panel/assets/stylesheets/panel.css
- rails_panel/manifest.json
- rails_panel/options.html
Refs https://github.com/dejan/rails_panel/issues/141
I did some minor changes to make it fully functional on Firefox.
1. Updated manifest to match newest standard as it was showing an error:
2. Updated Devtools tabs CSS
Before:
After:
3. Updated Options page to make it more responsive.
Before it was wider than the viewport:
After:
> Firefox support - minor style fixes

- .circleci/config.yml
- meta_request/Dockerfile-rails-4.2
- meta_request/docker-compose.yml
Rails 4.1 (from 2014-2016) doesn't work correctly with new Ruby versions and new gems.
It's sane to drop tests for it and test using more modern Rails 4.2 which latest version was released this year.
> Test Rails 4.2 instead of Rails 4.1

- .circleci/config.yml
- meta_request/Dockerfile-rails-6.1
- meta_request/docker-compose.yml
- meta_request/lib/meta_request/event.rb
Since Rails 6.1, the payload of action dispatch can't be converted.
It's not guaranteed `to_json` conversion, and `SystemStackError` got to happen.
To avoid this, fixed to ignore `ActionDispatch::Request/ActionDispatch::Response` to JSON.
and added test for rails 6.1
> Do not attempt to convert ActionDispatch::Request/Response to JSON

- .circleci/config.yml
- meta_request/Dockerfile-rails-4.2
- meta_request/Dockerfile-rails-5.0
- meta_request/Dockerfile-rails-5.1
- meta_request/Dockerfile-rails-6.0
- meta_request/Dockerfile-rails-6.1
- meta_request/Dockerfile-rails-7.0
- meta_request/docker-compose.yml
- meta_request/meta_request.gemspec
- meta_request/res/meta_request_test.rb
> Add Rails 7.0 to CI

- meta_request/meta_request.gemspec
The railties dependency was blocking compatibility with a new version,
after allowing it should be fine.
Fixes https://github.com/dejan/rails_panel/issues/180
> Add Rails 7.1 Support

- meta_request/.rubocop.yml
- meta_request/lib/meta_request/event.rb
- meta_request/spec/meta_request/event_spec.rb
When using a simple Rails view template like
```erb
<% cache User.all do %>
some content here
<% end %>
```
we noticed that a spurious SQL query
```sql
SELECT "users".* FROM "users"
```
was executed both on cache miss and on cache hit.
Since the very point of [fragment caching][1] is to prevent this kind of queries, we investigated and found out that they were caused by `meta_request`.
Rather than just stating the cache key used, events from `ActiveSupport::Cache` provide all original objects which contributed to the calculation of the cache key. This included `User.all` from the template.
When `meta_request` checks whether this object is encodable to JSON
```ruby
User.all.as_json(methods: [:duration])
```
unintentionally triggers the spurious SQL query.
We fix this by sanitizing the …
> Prevent spurious SQL query execution via ActiveSupport::Cache events

- meta_request/Dockerfile-rails-5.2
- meta_request/Dockerfile-rails-6.0
- meta_request/Dockerfile-rails-6.1
- meta_request/Dockerfile-rails-7.0
There were 2 issues that were breaking the build and tests.
1. Updating Ruby Gems itself without specifying a version causes it to update to the latest version which requires Ruby 3. Instead, we specify the latest version compatible with the installed Ruby.
Compatibility versions found here:
https://rubygems.org/api/v1/versions/rubygems-update.json
2. All builds were having issues with missing shared libraries. In the case of the Ruby 2.6 images it was nokogiri and for the Ruby 3.0 image it was sqlite3. A common fix for all the builds was to configure Bundler to consider the platform during dependency resolution.
More information found here:
https://bundler.io/v1.14/whats_new.html
https://github.com/sparklemotion/sqlite3-ruby/issues/434 https://github.com/github/pages-gem/issues/839 - …
> Fix the Docker build errors

- meta_request/lib/meta_request/config.rb
- meta_request/lib/meta_request/utils.rb
- meta_request/spec/meta_request/utils_spec.rb
- meta_request/spec/spec_helper.rb
(reviving #174 against the latest master)
> Ignore ./vendor & ./bin from stacktraces

- extension/src/App.vue
- extension/src/components/Requests.vue
- extension/src/components/Toolbar.vue
- extension/src/components/wrappers/SelectionTable.vue
- extension/src/components/wrappers/ToolbarButton.vue
- extension/src/components/wrappers/ToolbarToggle.vue
- extension/src/stores/events.js
- extension/src/stores/settings.js
Introduce a toggle to let the user _pin_ the selected request so it's not automatically deselected when the new requests arrive.
Resolves https://github.com/dejan/rails_panel/issues/165
> Implement pin feature

- extension/package-lock.json
- extension/package.json
- extension/src/components/ActionParams.vue
- extension/src/components/ActiveRecordQueries.vue
- extension/src/components/wrappers/ToolbarToggle.vue
- extension/src/style.css
Pretty print params so when they are nested, it's easier to understand the structure. See https://github.com/dejan/rails_panel/issues/44
> Pretty print params

- meta_request/Dockerfile-rails-7.1
- meta_request/lib/meta_request/event.rb
- meta_request/meta_request.gemspec
Due to Rails monkey patching the Object#to_json method, it is possible for an unassuming object to call the method and trigger a <SystemStackError: stack level too deep> error.
https://github.com/rails/rails/blob/v7.1.3.2/activesupport/lib/active_support/core_ext/object/json.rb#L63
We discovered a case where this was caused by an instance of ActionView::Helpers::FormBuilder. We extended MetaRequest::Event#not_encodable? to exclude this class and prevent the recursion.
> Rails 7.1 Incompatibility: Exclude Payload Locals

- meta_request/Dockerfile-rails-7.2
- meta_request/docker-compose.yml
- meta_request/lib/meta_request/event.rb
On trying to upgrade to Rails 7.2, I was experiencing
[SystemStackError: stack level too deep (SystemStackError)]
On debugging, I found the object triggering this was an instance of ActiveRecord::Transaction:
```ruby
=> #<ActiveRecord::Transaction:0x00000001211be2a8
@internal_transaction=
#<ActiveRecord::ConnectionAdapters::RealTransaction:0x0000000121b1a298
@callbacks=nil,
@connection=#<ActiveRecord::ConnectionAdapters::PostgreSQLAdapter:0x0000000000ec40 env_name="development" role=:writing>,
@dirty=false,
@instrumenter=
#<ActiveRecord::ConnectionAdapters::TransactionInstrumenter:0x00000001211be258
@base_payload=
{:connection=>#<ActiveRecord::ConnectionAdapters::PostgreSQLAdapter:0x0000000000ec40 env_name="development" role=:writing>, …
```
> Improve Rails 7.2 compatibility

- README.md
- meta_request/Dockerfile-rails-8.0
- meta_request/docker-compose.yml
- meta_request/meta_request.gemspec
In addition to checking the results in `docker compose up`, I tested this with a brand new Rails 8 app and it seemed to work just fine.
> Support rails 8
